# Generated by Django 5.1 on 2024-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='name',
            field=models.TextField(max_length=264, unique=True),
        ),
    ]
